---
# Generate Certificate Authority, where the create_ca tag has been specified
- hosts: authority
  become: yes
  gather_facts: yes
  roles:
    - role: absvfx.authority
      tags:
        - create_ca
  tags:
    - create_ca

# Configure AbsVFX Dev Server
- hosts: authority
  connection: ssh
  become: yes
  gather_facts: yes
  roles:
    - role: absvfx.docker
    - role: absvfx.kubernetes
