---
# Create Initial Directory Structure
- include_tasks: populate.yml
  vars:
    authority_root: "{{ root_authority_directory }}"
    openssl_configuration_template: openssl.cnf.j2

# Generate Root CA Key
- name: generate root ca key
  openssl_privatekey:
    path: "{{ root_authority_directory }}/private/ca.key.pem"
    passphrase: "{{ nzb_tertiary_newsserver_password }}"
    size: 4096
    cipher: aes256
  tags:
    - create_ca
    
# Generate Root CA Certificate
# TODO: Modify openssl_crl / openssl_certificate module to allow custom configuration files
- name: generate root ca certificate
  shell: "openssl req -config {{ root_authority_directory }}/openssl.cnf -key {{ root_authority_directory }}/private/ca.key.pem -new -x509 -days 7300 -sha256 -extensions v3_ca -passin pass:{{ nzb_tertiary_newsserver_password }} -subj \"/C={{ root_authority_country }}/ST={{ root_authority_state }}/O={{ root_authority_organization }}/CN={{ root_authority_hostname }}\" -out {{ root_authority_directory }}/certs/ca.cert.pem"
  tags:
    - create_ca

### INTERMEDIATE CERT
# Create Initial Directory Structure
- include_tasks: populate.yml
  vars:
    authority_root: "{{ root_authority_directory }}/intermediate"
    openssl_configuration_template: intermediate.openssl.cnf.j2

# Generate Intermediate CA Key
- name: generate intermediate ca key
  openssl_privatekey:
    path: "{{ root_authority_directory }}/intermediate/private/ca.key.pem"
    passphrase: "{{ nzb_tertiary_newsserver_password }}"
    size: 4096
    cipher: aes256
  tags:
    - create_ca

# Generate Intermediate CA Certificate
# TODO: Modify openssl_crl / openssl_certificate module to allow custom configuration files
- name: generate intermediate ca certificate
  shell: "openssl req -config {{ root_authority_directory }}/intermediate/openssl.cnf -key {{ root_authority_directory }}/intermediate/private/ca.key.pem -new -x509 -days 7300 -sha256 -extensions v3_ca -passin pass:{{ nzb_tertiary_newsserver_password }} -subj \"/C={{ root_authority_country }}/ST={{ root_authority_state }}/O={{ root_authority_organization }}/CN={{ root_authority_hostname }}\" -out {{ root_authority_directory }}/intermediate/certs/ca.cert.pem"    
  tags:
    - create_ca

# Combine Root & Intermediate Certificate in to a single file
- name: combine ca cert
  shell: "cat {{ root_authority_directory }}/intermediate/certs/ca.cert.pem {{ root_authority_directory }}/certs/ca.cert.pem > {{ root_authority_directory }}/intermediate/certs/ca-chain.cert.pem"
  tags:
    - create_ca

# GENERATE SERVER SSL CERTIFICATE
# Request hostname of the node being targeted
- name: store target hostname
  set_fact:
    target_hostname: "{{ inventory_hostname }}"

# Randomly select an available authority node for use on further tasks
- name: select authority to use
  set_fact:
    target_authority_node: "{{ item }}"
  with_random_choice: "{{ groups['authority'] }}"

# Generate Server SSL Key
- name: generate ssl certificate key
  openssl_privatekey:
    path: "{{ root_authority_directory }}/intermediate/certs/{{ target_hostname }}.key.pem"
    size: 2048
  delegate_to: "{{ target_authority_node }}"
  tags:
    - generate_certs

# Generate Server Certificate Request
- name: generate ssl certificate request
  openssl_csr:
    path: "{{ root_authority_directory }}/intermediate/certs/{{ target_hostname }}.csr.pem"
    privatekey_path: "{{ root_authority_directory }}/intermediate/certs/{{ target_hostname }}.key.pem"
    country_name: "{{ root_authority_country }}"
    organization_name: "{{ root_authority_organization }}"
    common_name: "{{ target_hostname }}"
  delegate_to: "{{ target_authority_node }}"
  tags:
    - generate_certs

# Generate Server SSL Certificate
- name: generate ssl certificate
  openssl_certificate:
    path: "{{ root_authority_directory }}/intermediate/newcerts/{{ target_hostname }}.crt"
    csr_path: "{{ root_authority_directory }}/intermediate/certs/{{ target_hostname }}.csr.pem"
    ownca_path: "{{ root_authority_directory }}/intermediate/certs/ca-chain.cert.pem"
    ownca_privatekey_path: "{{ root_authority_directory }}/intermediate/private/ca.key.pem"
    ownca_privatekey_passphrase: "{{ nzb_tertiary_newsserver_password }}"
    provider: ownca
  delegate_to: "{{ target_authority_node }}"
  tags:
    - generate_certs

# Create SSL Certificate Directory on node
- name: create directory structure if missing
  file:
    path: "/etc/absvfx/ssl/certs"
    state: directory

# Transfer ca certificate to the Ansible controller (to avoid rsync issues with the synchronize module)
- name: transfer ca certificate (local)
  fetch:
    src: "{{ root_authority_directory }}/intermediate/certs/ca-chain.cert.pem"
    dest: "/tmp/ca.crt"
    remote_src: yes
    flat: yes
  delegate_to: "{{ target_authority_node }}"
  tags:
    - generate_certs

# Transfer generated key to the Ansible controller (to avoid rsync issues with the synchronize module)
- name: transfer ssl key (local)
  fetch:
    src: "{{ root_authority_directory }}/intermediate/certs/{{ target_hostname }}.key.pem"
    dest: "/tmp/{{ target_hostname }}.key"
    remote_src: yes
    flat: yes
  delegate_to: "{{ target_authority_node }}"
  tags:
    - generate_certs

# Transfer generated certificate to the Ansible controller (to avoid rsync issues with the synchronize module)
- name: transfer ssl certificate (local)
  fetch:
    src: "{{ root_authority_directory }}/intermediate/newcerts/{{ target_hostname }}.crt"
    dest: "/tmp/{{ target_hostname }}.crt"
    remote_src: yes
    flat: yes
  delegate_to: "{{ target_authority_node }}"
  tags:
    - generate_certs

# Transfer generated key to the remote node (to avoid rsync issues with the synchronize module)
- name: transfer ca certificate
  copy:
    src: /tmp/ca.crt
    dest: /etc/absvfx/ssl/certs/ca.crt
  tags:
    - generate_certs

# Transfer generated key & certificate to the remote node (to avoid rsync issues with the synchronize module)
- name: transfer ssl key & cert
  copy:
    src: "/tmp/{{ target_hostname }}.{{ item }}"
    dest: "/etc/absvfx/ssl/certs/{{ target_hostname }}.{{ item }}"
  loop:
    - crt
    - key
  tags:
    - generate_certs

# Clean up the local copy of data
- name: remove certificate data from /tmp
  file:
    state: absent
    path: "/tmp/{{ item }}"
  loop:
    - ca.crt
    - "{{ target_hostname }}.crt"
    - "{{ target_hostname }}.key"
  tags:
    - generate_certs

# Grant access to the generated certificates to all users
- name: set certificate permissions
  file:
    path: "/etc/absvfx/ssl/certs/{{ item }}"
    owner: root
    group: root
    mode: '1755'
  loop:
    - "{{ target_hostname }}.crt"
    - "{{ target_hostname }}.key"
    - "ca.crt"
  tags:
    - generate_certs
