---
- name: generate jenkins ssl certs
  include_role:
    name: absvfx.authority
    apply:
      tags:
        - generate_certs

- name: create jenkins docker volume for certificates
  docker_volume:
    name: jenkins_certs
    state: present

- name: copy ssl certificates to docker volume
  shell: "docker run --rm -v jenkins_certs:/certs -v /etc/absvfx/ssl/certs/:/certs_host alpine cp /certs_host/{{ item }} /certs/{{ item }}"
  loop:
    - ca.crt
    - "{{ target_hostname }}.crt"
    - "{{ target_hostname }}.key"
