---
- name: obtain datetime
  shell: "date +%Y%m%d-%H%M%S"
  register: time
  tags: backup

- name: save current state of container
  shell: "docker export {{ item.name }} > /tmp/{{ item.name }}_container_{{ time.stdout }}.tgz"
  loop:
    - "{{ docker_containers|list }}"
  tags: backup

- name: copy container backups
  fetch:
    src: "/tmp/{{ item.name }}_container_{{ time.stdout }}.tgz"
    dest: "{{ backup_directory }}"
  loop:
    - "{{ docker_containers|list }}"
  tags: backup

- name: remove container backups from node
  file:
    path: "/tmp/{{ item.name }}_container_{{ time.stdout }}.tgz"
    state: absent
  loop:
    - "{{ docker_containers|list }}"
  tags: backup

- name: compress container volumes
  archive:
    path: "/opt/docker/{{ item.name }}"
    dest: "/tmp/{{ item.name }}_volume_{{ time.stdout }}.tgz"
  tags: backup

- name: copy container volumes
  fetch:
    src: "/tmp/{{ item.name }}_volume_{{ time.stdout }}.tgz"
    dest: "{{ backup_directory }}"
  loop:
    - "{{ docker_containers|list }}"
  tags: backup

- name: remove container volume backups from node
  file:
    path: "/tmp/{{ item.name }}_volume_{{ time.stdout }}.tgz"
    state: absent
  loop:
    - "{{ docker_containers|list }}"
  tags: backup
