---
# Generate SSL Certificates for Docker
# - name: generate docker ssl certs
#   include_role:
#     name: absvfx.authority
#     apply:
#       tags:
#         - generate_certs

- name: add docker-ce yum repository
  shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  tags: install
  when: ansible_facts['distribution'] == "Centos"

- name: install docker
  package:
    name: "{{ item }}"
  loop:
    - docker-ce
  tags:
    - install
    - update
  when: ansible_facts['distribution'] == "Centos"

- name: install docker
  package:
    name: "{{ item }}"
  loop:
    - docker
  tags:
    - install
    - update
  when: ansible_facts['distribution'] == "Archlinux"

# Copy systemd Service
- name: copy docker systemd service
  copy:
    src: /usr/lib/systemd/system/docker.service
    dest: /etc/systemd/system/docker.service
    remote_src: yes

# Modify systemd service for listening on TLS
- name: allow tls connections
  lineinfile:
    path: /etc/systemd/system/docker.service
    regexp: '^ExecStart='
    line: "ExecStart=/usr/bin/dockerd -H fd:// -H {{ inventory_hostname }}:2376 --tlsverify --tlscacert=/etc/absvfx/ssl/certs/ca.crt --tlscert=/etc/absvfx/ssl/certs/{{ inventory_hostname }}.crt --tlskey=/etc/absvfx/ssl/certs/{{ inventory_hostname }}.key"
  tags:
    - update
  vars:
    common_name: docker.absvfx.xyz

# Change cgroup driver from cgroupfs to systemd
- name: apply custom docker daemon config
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"

# Allow TLS Docker Connections through firewall
- name: allow docker through firewall
  firewalld:
    port: 2376/tcp
    permanent: yes
    state: enabled
    zone: vpn

- name: reload systemd daemon
  shell: systemctl daemon-reload
  tags:
    - update

- name: enable and start docker
  systemd:
    state: started
    enabled: yes
    name: "docker"
  tags: install

- name: restart docker service
  systemd:
    state: restarted
    name: "docker"
  tags: update

- name: install docker pip module
  pip:
    name: docker
  tags:
    - install
    - update
